### ISSUE TITLE
Can't retrieve test_july_22 trips using e-mission-phone app in iOS simulator.

### ISSUE THREAD

**Issue by asiripanich** [cityverse/e-mission-devenv#1]
The test trips do appear in Mongodb and loadable using the analysis script provided by Shankari. @atton16 Could you please look into this?

**Comment by atton16** [comment]
`test_july_22` file needed, sir.

**Comment by asiripanich** [comment]
As stated in the `Load testing data` section of the readme of [e-mission-phone](https://github.com/e-mission/e-mission-server/blob/master/README.md).

**Comment by atton16** [comment]
Fixed
